stages:
  - release-docker

.images: &images
  image: docker:17.06
  stage: release-docker
  services:
    - docker:17.06-dind
  variables:
    DOCKER_DRIVER: overlay
  tags:
    - docker
  only:
    - tags
  script:
    - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$CI_COMMIT_SHA --build-arg VERSION=$(echo $CI_COMMIT_TAG | sed 's|v||') -t klud/$CI_JOB_NAME:$(echo $CI_COMMIT_TAG | sed 's|v||') .
    - docker tag klud/$CI_JOB_NAME:$(echo $CI_COMMIT_TAG | sed 's|v||') klud/$CI_JOB_NAME:latest
    - docker tag klud/$CI_JOB_NAME:$(echo $CI_COMMIT_TAG | sed 's|v||') $CI_REGISTRY_IMAGE:$(echo $CI_COMMIT_TAG | sed 's|v||')
    - docker tag klud/$CI_JOB_NAME:$(echo $CI_COMMIT_TAG | sed 's|v||') $CI_REGISTRY_IMAGE:latest
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push $CI_REGISTRY_IMAGE
    - docker push klud/$CI_JOB_NAME
    - docker logout $CI_REGISTRY
    - docker logout

docker-gql: *images
